import Foundation

/// Source for the OpenCode plugin that bridges OpenCode's plugin events to
/// Supacode's OSC 3008 agent-presence protocol.
///
/// OpenCode does NOT consume a Claude-style declarative `hooks` block in its
/// config (`opencode.json`). Its extensibility surface is JS/TS plugins
/// auto-loaded from `~/.config/opencode/plugins/`. So instead of writing a
/// settings file, Supacode installs a small plugin that runs the exact same
/// guarded shell command every other agent's hooks run — keeping the OSC
/// template, surface guard, tty resolve, and pid-liveness suffix single-sourced
/// in `AgentHookSettingsCommand`.
nonisolated enum OpenCodePluginContent {
  /// File name written under `~/.config/opencode/plugins/`.
  static let pluginFileName = "supacode-presence.js"

  /// Marker that identifies a Supacode-managed plugin file. The composite
  /// command embeds `AgentHookSettingsCommand.ownershipMarker` verbatim, so the
  /// generated source always contains it — uninstall keys off this so it never
  /// deletes a user file that merely shares the name.
  static let ownershipMarker = AgentHookSettingsCommand.ownershipMarker

  /// Deterministic plugin source (no timestamps), so `installState` can detect
  /// a byte-for-byte match vs. an older Supacode version's plugin (`.outdated`).
  static func source() -> String {
    """
    // \(ownershipMarker)
    //
    // Generated by Supacode — do not edit. Bridges OpenCode plugin events to
    // Supacode's OSC 3008 agent-presence protocol by running the same guarded
    // shell command Supacode installs for every other agent. The command checks
    // SUPACODE_SURFACE_ID first, so it is inert outside a Supacode surface and
    // safe to keep installed anywhere.
    //
    // Presence only: OpenCode's session.idle event carries no assistant text
    // (unlike Claude Code's Stop hook stdin), so the system-notification leg is
    // intentionally omitted rather than fed a fabricated body.
    export const SupacodePresence = async ({ $ }) => {
      const emit = (command) => $`sh -c ${command}`.quiet().nothrow()

      // Agent is now present in this surface.
      await emit(\(jsString(command(for: [.sessionStart]))))

      return {
        // Agent (and its surface presence) is going away.
        dispose: async () => {
          await emit(\(jsString(command(for: [.sessionEnd, .idle]))))
        },
        // Tool-level activity shimmer: a tool started / finished.
        "tool.execute.before": async () => {
          await emit(\(jsString(command(for: [.busy]))))
        },
        "tool.execute.after": async () => {
          await emit(\(jsString(command(for: [.idle]))))
        },
        // A permission prompt is the "needs you" state.
        "permission.ask": async () => {
          await emit(\(jsString(command(for: [.awaitingInput]))))
        },
        event: async ({ event }) => {
          if (event.type === "session.idle") {
            await emit(\(jsString(command(for: [.idle]))))
          } else if (event.type === "permission.replied") {
            await emit(\(jsString(command(for: [.busy]))))
          }
        },
      }
    }
    """
  }

  private static func command(for events: [HookEvent]) -> String {
    AgentHookSettingsCommand.compositeCommand(
      events: events, forwardStdinAsNotification: false, agent: .opencode)
  }

  /// JSON-encoding a `String` yields a valid double-quoted JavaScript string
  /// literal: it escapes `"`, `\`, and control characters, and the composite
  /// command contains no newlines. `$` and backticks are literal inside a
  /// double-quoted JS string, so no extra escaping is needed.
  private static func jsString(_ value: String) -> String {
    guard
      let data = try? JSONEncoder().encode(value),
      let literal = String(data: data, encoding: .utf8)
    else {
      return "\"\""
    }
    return literal
  }
}
